# Generated by Django 2.2.2 on 2019-06-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20190624_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messaginggroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
