# Generated by Django 2.2.2 on 2019-06-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20190624_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
